services:

  HeimrichHannot\PrivacyProtocolBundle\:
    resource: '../src/{DataContainer}/*'
    autowire: true
    autoconfigure: true
    public: false

  HeimrichHannot\PrivacyProtocolBundle\Protocol\PrivacyProtocolLogger:
    autowire: true
    public: true